### PR TITLE
Cleaned up startup.cs

### PR DESCRIPTION
**Pull request by ghost**
Cleaned up startup.cs by introducing ServiceCollectionExtensions, which contains the ' logic'. It will reduce the number of lines in Startup and give more overview.

### CODE REVIEW

**Comment by amoraitis** [comment]
Let me test the changes locally. I think this is an awesome update for the project.

Thank you @RemcoE

**Comment by ghost** [comment]
For this kind of PR's (Startup.cs changes) it's hard to increase code coverage. What is your opinion about this? It's not passing the 'code coverage' requirement right now.

**Comment by ghost** [comment]
This also applies to #34

**Comment by amoraitis** [comment]
> For this kind of PR's (Startup.cs changes) it's hard to increase code coverage. What is your opinion about this? It's not passing the 'code coverage' requirement right now.

Hi @reerden, I will merge anyway, and there is a way to test the services collection. But, I don't really care about codecov.

**Review by amoraitis — APPROVED** [review]

**Pull request closed without merging**
