### PR TITLE
Introduce TodoList.API 

### PR DESCRIPTION
**Pull request by jenia90**
Referencing #44 .
Hope I haven't missed anything. Also, I still have to write tests for the controller, which I will do in a separate PR.

### CODE REVIEW

**Comment by amoraitis** [comment]
Please change the target branch to `feature/#44-todolist-api`

**Comment by amoraitis** [comment]
@jenia90 I will merge it for now and I will introduce some updates later, such as including it to the docker-compose file

**Comment by jenia90** [comment]
> 
> 
> @jenia90 I will merge it for now and I will introduce some updates later, such as including it to the docker-compose file

Do you plan to make the MVC app talk to the API? Or just leave it talking to the repository directly?

**Comment by amoraitis** [comment]
Yes the MVC will implement http clients.

**Pull request merged**
