### PR TITLE
resolve #5 by adding gravatar support

### LINKED ISSUE #5: [Feature] Add gravatar for users
**Is your feature request related to a problem? Please describe.**
It would be nice if we integrate and use [gravatar](gravatar.com/) for a default user icon.

**Describe the solution you'd like**

- [x] Use `GravatarHelper.AspNetCore`

- [x] Retriεve it in the top-right menu instead of "Hi {username}" 

- [x] and User's profile page

**Additional context**
Default size for menu-icon=20
Default size for profile-icon=60

### PR DESCRIPTION
**Pull request by Hameds**
I used `GravatarHelper.AspNetCore`  [NuGet package] (https://www.nuget.org/packages/GravatarHelper.AspNetCore/) to add support for gravatar (#5) instead of storing user hashed email in db which is clean and reusable.

### CODE REVIEW

**Review by amoraitis — CHANGES_REQUESTED** [review]
It would be also nice, if we had the icon in the top menu changed with the gravatar

**Comment by Hameds** [comment]
@amoraitis Do you mean something like this?
capture

**Comment by amoraitis** [comment]
> @amoraitis Do you mean something like this?
> capture

@Hameds please commit the changes to merge it, we dont have a dropown menu yet

**Comment by Hameds** [comment]
@amoraitis I added gravatar support to the menu. I will continue to work on the dropdown menu and I will send another PR for that

**Review by amoraitis — DISMISSED** [review]

**Review by amoraitis — APPROVED** [review]

**Comment by amoraitis** [comment]
Please update your repo and create a new PR @Hameds For details see https://github.com/amoraitis/TodoList/blob/develop/SETUP_GUIDELINES.md

**Comment by Hameds** [comment]
@amoraitis sure. I will do that

**Pull request merged**
